CREATE DATABASE IF NOT EXISTS CMSC_4003;

CREATE USER IF NOT EXISTS 'CMSC_4003_USER'@'localhost' IDENTIFIED BY 'password123';
GRANT ALL PRIVILEGES ON CMSC_4003.* TO 'CMSC_4003_USER'@'localhost';
FLUSH PRIVILEGES;
